### ISSUE TITLE
error undetected before alloy parsing

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#19]
In the following extract, constraints should apply to entries instead of map.
This is undetected by the python program, and Alloy reports on the model an incorrect call to predicate TOSCA/min_length[] due to incorrect argument types, which is a consequence of the pb as stated above.
![image](https://user-images.githubusercontent.com/36159682/100886878-9eecaa80-34b4-11eb-90fc-6392a4e98794.png)

**Comment by philippemerle** [comment]
In this extract, the constraint min_length must be applied on the map, i.e. at least one entry is required in the map, and not on each entry. This constraint would be evaluated by the Python code: this must be addressed by issue #16.
I think that here the problem is in the generated Alloy code.
Could you post the generated Alloy code and the error reported by Alloy?

**Comment by fredkgit** [comment]
Oups, I'm going to fast. Ok. 
It was several days ago, but if I remember well, it's in this template I saw the map key wasn't a String, but some datatype with one property of type Int (or  alike). Also since 1.3 there are key_schemas for maps, so min_length[) may become more complicated.
Here are the trace and the generated alloy code (txt to be renamed als)
[trace_issue_19.txt](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/5630693/trace_issue_19.txt)
[etsi_nfv_sol001_nsd_types_3_3_3.txt](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/5630760/etsi_nfv_sol001_nsd_types_3_3_3.txt)

**Comment by fredkgit** [comment]
It's half a mistake here, there's no issue which would not be taken into account in #16. So it's closed.
