### ISSUE TITLE
Improve type checkings

### ISSUE THREAD

**Issue by philippemerle** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#8]
Add more type checkings to the Cloudnet TOSCA toolchain to detect errors the earlier. 
Check that 
1. declared types are not already defined
2. used types are defined
3. used types are of the expected type kind, e.g. if "capability: x" then x is a capability type
4. acyclic depend from
5. overloading fields refering a type
6. property values are of the right type

etc.

**Comment by fredkgit** [comment]
I think it's a good idea to clearly separate the alloy generator from type system checking and improve the type checking as mentionned above. I suppose issue #13 is part of (1) 'declared types are not already defined'

**Comment by philippemerle** [comment]
yes issue #13 is related to 'declared types are not already defined'.

**Comment by fredkgit** [comment]
For (1.), for ETSI NFV 3.5.1, I recently had the following error report because in the NSD types the policy for NS instantiation levels was defined with the same name as the similar policy for VNF (not identical), i.e. the name was tosca.policies.nfv.InstantiationLevels instead of  tosca.policies.nfv.NsInstantiationLevels .
[issue_8_ambiguous_naming.txt](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/5630867/issue_8_ambiguous_naming.txt)

**Comment by JLCoulin** [comment]
Closed with merge [ff54839](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/ff54839b006840b2923ebc386c84f35d93384728)
